version: '3.8'

# --- 1. Define all Services ---
services:
  # --- Monitoring Services ---
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    networks:
      - arpanet # Fixed from happenhub-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: happenhub-pass
    depends_on:
      - prometheus
    networks:
      - arpanet # Fixed from happenhub-network

# --- 2. Define all Volumes for Persistence ---
volumes:
  prometheus_data: {}
  grafana_data: {}

# --- 3. Define all Networks ---
networks:
  arpanet:
    driver: bridge # This creates the network for all services
